<?php
declare(strict_types=1);

namespace noFlash\NotifyBot;

use noFlash\NotifyBot\Command\AvailabilityCommand;
use noFlash\NotifyBot\Command\NotifyCommand;
use Symfony\Component\Console\Application as SymfonyApplication;

class Application extends SymfonyApplication
{
    private const APP_NAME = "NotifyBot";
    private const APP_VER  = 'v0.1';

    /**
     * @var NotifyCommand
     */
    private $notifyCommand;

    /**
     * @var AvailabilityCommand
     */
    private $availabilityCommand;

    public function __construct(
        NotifyCommand $notifyCommand,
        AvailabilityCommand $availabilityCommand)
    {
        $this->notifyCommand = $notifyCommand;
        $this->availabilityCommand = $availabilityCommand;

        parent::__construct(self::APP_NAME, self::APP_VER);
    }

    protected function getDefaultCommands()
    {
        $cmds = parent::getDefaultCommands(); // TODO: Change the autogenerated stub

        $cmds[] = $this->notifyCommand;
        $cmds[] = $this->availabilityCommand;

        return $cmds;
    }
}
